alias Demand.List

List.new("Toppings")
|> List.description("List of available toppings")
|> List.item("Lettuce")
|> List.item("Tomatoes")
|> List.item("Charm Sauce")
|> List.item("Jalapenos")
|> List.item("Cheese")
|> List.item("Vegan Cheese")
|> List.item("Nutella")
|> List.item("Peanut Butter")
|> List.item("Banana")
|> List.item("Strawberries")
|> List.item("Blueberries")
|> List.item("Pineapple")
|> List.item("Mango")
|> List.item("Kiwi")
|> List.item("Passion Fruit")
|> List.item("Peaches")
|> List.item("Raspberries")
|> List.item("Blackberries")
|> List.item("Mint")
|> List.item("Chocolate Chips")
|> List.item("Oreos")
|> List.item("Brownie Bites")
|> List.item("Cookie Dough")
|> List.item("Graham Cracker Crumbs")
|> List.item("M&Ms")
|> List.item("Reese's Pieces")
|> List.item("Butterfinger")
|> List.item("Heath Bar")
|> List.item("Kit Kat")
|> List.item("Snickers")
|> List.item("Twix")
|> List.item("Caramel")
|> List.item("Hot Fudge")
|> List.item("Marshmallow")
|> List.item("Whipped Cream")
|> List.item("Chocolate Syrup")
|> List.item("Caramel Syrup")
|> List.item("Strawberry Syrup")
|> List.item("Peanut Butter Syrup")
|> List.item("Nutella Syrup")
|> List.item("Honey")
|> List.item("Sprinkles")
|> List.item("Chocolate Sprinkles")
|> List.item("Coconut Flakes")
|> List.item("Almonds")
|> List.item("Peanuts")
|> List.item("Walnuts")
|> List.item("Pecans")
|> List.item("Cashews")
|> List.item("Pistachios")
|> List.item("Macadamia Nuts")
|> List.item("Hazelnuts")
|> List.item("Peanut Butter Cups")
|> List.item("Gummy Bears")
|> List.item("Sour Patch Kids")
|> List.item("Sour Gummy Worms")
|> List.item("Sour Skittles")
|> List.item("Skittles")
|> List.item("Starburst")
|> List.item("Twizzlers")
|> List.item("Milk Duds")
|> List.filterable(true)
|> List.run()
|> case do
  {:ok, item} -> IO.puts("You selected: #{item}")
  _ -> IO.puts("Aborted")
end
